name: Continuous Delivery

on:
  push:
    branches: main

jobs:
  delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        run: |
          docker build -t acnaweb/java-ping .
          docker push acnaweb/java-ping